In [78]:
## Python Variable and Data Types
#string
name = "Heather" 
#float
salary = 58531.20 
#integer
age = 30 
#Boolean
married = True 


### Get data from the user from the input function
name = input("Welcome to XYZ currency exchange, please enter your name:")
amount_USD = 1
amount_CAD = 25

In [79]:
print("Welcome {}, the equivalent of USD$ {} is CAD ${}".format(name,amount_USD,amount_CAD))

Welcome , the equivalent of USD$ 1 is CAD $25

In [80]:
name = input( "Welcome to Indian stock exchange, What is your name?")
name
amount_USD = input( "Enter the amount you would like to exhange in USD: ")
amount_USD

''

In [81]:
amount_USD = float(amount_USD)
type(amount_USD)
USD_CAD = 1.36
amount_CAD = amount_USD*USD_CAD
amount_CAD

ValueError: could not convert string to float: ''

In [ ]:
print("Welcome {}, the equivalent of USD${} is CAD ${}".format(name,amount_USD,amount_CAD))

Welcome Ryan, the equivalent of USD$1000.0 is CAD $1360.0

In [ ]:
### Practice Opportunity
name = input("What is your name?:")
amount_SGD = input("How many SGDs you want to exchange for USD?:")
amount_SGD = float(amount_SGD)
USD_SGD = 1.34
amount_USD = amount_SGD/USD_SGD
print("You'd receive ${}.Do you want to continue {}?".format(amount_USD,name))

You'd receive $10000.0.Do you want to continue Ronaldo?

In [ ]:
##Python List, Loops and List Comprehension

input_list = [1,2,3,4,5]
output_list = []
for x in input_list:
    output_list.append(x**2)
print(output_list)

output_list = [x**2 for x in input_list]
output_list

## Practice Opportunity
client_investments = [400000,45000,60000]
returns_list = []
for x in client_investments:
    returns_list.append(x*0.08)
print(returns_list)

returns_list = [x*0.08 for x in client_investments]
returns_list

[1, 4, 9, 16, 25]
[32000.0, 3600.0, 4800.0]

[32000.0, 3600.0, 4800.0]

In [ ]:
### Lambda, Built-IN and Python Functions

## User Defined Functions (def)
def multiply(x,y):
    z = x*y
    return z
multiply(2,5)


## Lambda Functions (simple one line)
z = lambda x,y : x*y
z(3,5)

## Built in Functions
buildin_fuctions = ['__build_class__',
 '__import__',
 'abs',
 'all',
 'any',
 'ascii',
 'bin',
 'callable',
 'chr',
 'compile',
 'delattr',
 'dir',
 'divmod',
 'eval',
 'exec',
 'format',
 'getattr',
 'globals',
 'hasattr',
 'hash',
 'hex',
 'id',
 'isinstance',
 'issubclass',
 'iter',
 'len',
 'locals',
 'max',
 'min',
 'next',
 'oct',
 'ord',
 'pow',
 'print',
 'repr',
 'round',
 'setattr',
 'sorted',
 'sum',
 'vars',
 'open']

company_revenue = [600000,500000,1000000,1100000,1500000]
len(company_revenue)
max(company_revenue)
min(company_revenue)

500000

In [ ]:
### Practice Opportunity
## Effective_rate = ((1 + (Interest/Period per year)) ^ Period per year) − 1
### Assume you deposited USD10,000 today into an account paying 6% compounded monthly. What is the expected effective rate of return?

effective_rate = lambda interest, period : ((1+(interest/period))**period)-1
effective_rate = effective_rate(0.06,12)

print("The effective annual interest rate = {}%".format(effective_rate*100))
amount_0 = 10000
print("The total interest earned by the end of year 1 = ${}".format(effective_rate*amount_0))

The effective annual interest rate = 6.167781186449828%
The total interest earned by the end of year 1 = $616.7781186449828

In [ ]:
### Data Collection Wrangling and Feature Engineering in ML

### Data Wrangling: Data wrangling involves cleaning and organising raw dataset by merging multiple sources of data, handling missing values and converting data from one format to another.

### Feature Engineering: Feature engineering involves transforming features in a dataset with the goal of improving the performance of downstream machine learning models. Feature engineering involves feature selection, scaling and creating new features from existing ones.

ModuleNotFoundError: No module named 'simfin'

In [ ]:
!pip install simfin
import simfin as sf
import pandas as pd

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\nikhi\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer.exe is installed in 'C:\Users\nikhi\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Collecting simfin
  Downloading simfin-1.0.2-py3-none-any.whl.metadata (637 bytes)
Collecting pandas (from simfin)
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy (from simfin)
  Downloading numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting requests (from simfin)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\nikhi\AppData\Roaming\Python\Python314\site-packages (from pandas->simfin) (2.9.0.post0)
Collecting tzdata (from pandas->simfin)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\nikhi\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas->simfin) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests->simfin)
  Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests->simfin)
  Downloading idna-3.15-py3-none-any.whl.metadata (7.7 kB)
Collecting urllib3<3,>=1.26 (from requests->simfin)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests->simfin)
  Downloading certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Downloading simfin-1.0.2-py3-none-any.whl (61 kB)
Downloading numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ----------------- ---------------------- 5.5/12.5 MB 28.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 31.3 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 28.0 MB/s  0:00:00
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ----------------------------- ---------- 7.3/9.9 MB 37.8 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 32.9 MB/s  0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl (159 kB)
Downloading idna-3.15-py3-none-any.whl (72 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.5.20-py3-none-any.whl (134 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: urllib3, tzdata, numpy, idna, charset_normalizer, certifi, requests, pandas, simfin

   ---------------------------------------- 0/9 [urllib3]
   ---------------------------------------- 0/9 [urllib3]
   ---- ----------------------------------- 1/9 [tzdata]
   ---- ----------------------------------- 1/9 [tzdata]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   -------- ------------------------------- 2/9 [numpy]
   ------------- -------------------------- 3/9 [idna]
   ----------------- ---------------------- 4/9 [charset_normalizer]
   ----------------- ---------------------- 4/9 [charset_normalizer]
   ----------------- ---------------------- 4/9 [charset_normalizer]
   -------------------------- ------------- 6/9 [requests]
   -------------------------- ------------- 6/9 [requests]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ------------------------------- -------- 7/9 [pandas]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ----------------------------------- ---- 8/9 [simfin]
   ---------------------------------------- 9/9 [simfin]

Successfully installed certifi-2026.5.20 charset_normalizer-3.4.7 idna-3.15 numpy-2.4.6 pandas-3.0.3 requests-2.34.2 simfin-1.0.2 tzdata-2026.2 urllib3-2.7.0

In [ ]:
sf.set_api_key("4c2831f8-3e71-46d5-9a98-689ae779486a")
sf.set_data_dir("~/simfin_data/")

In [ ]:
income_df = sf.load_income(variant = "quarterly", market = "us").reset_index()
income_df

Dataset "us-income-quarterly" on disk (0 days old).
- Loading from disk ... Done!

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
0,A,2020-07-31,45846,USD,2020,Q3,2020-09-01,2021-09-01,309000000.0,312000000.0,...,-11000000.0,-18000000.0,219000000.0,NaN,219000000,-20000000.0,199000000,NaN,199000000,199000000
1,A,2020-10-31,45846,USD,2020,Q4,2020-12-18,2021-09-01,308000000.0,311000000.0,...,-16000000.0,-18000000.0,283000000.0,NaN,283000000,-61000000.0,222000000,NaN,222000000,222000000
2,A,2021-01-31,45846,USD,2021,Q1,2021-03-02,2022-03-03,306000000.0,309000000.0,...,-16000000.0,-19000000.0,312000000.0,NaN,312000000,-24000000.0,288000000,NaN,288000000,288000000
3,A,2021-04-30,45846,USD,2021,Q2,2021-06-01,2022-05-31,306000000.0,306000000.0,...,-15000000.0,-19000000.0,273000000.0,NaN,273000000,-57000000.0,216000000,NaN,216000000,216000000
4,A,2021-07-31,45846,USD,2021,Q3,2021-09-01,2022-09-01,303000000.0,306000000.0,...,-9000000.0,-21000000.0,327000000.0,NaN,327000000,-63000000.0,264000000,NaN,264000000,264000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50032,ZYXI,2024-03-31,171401,USD,2024,Q1,2024-04-30,2025-04-29,32344000.0,32827000.0,...,-512000.0,-512000.0,13000.0,NaN,13000,-3000.0,10000,NaN,10000,10000
50033,ZYXI,2024-06-30,171401,USD,2024,Q2,2024-07-25,2025-07-31,31762000.0,32204000.0,...,-630000.0,-630000.0,1596000.0,19000.0,1615000,-398000.0,1217000,NaN,1217000,1217000
50034,ZYXI,2024-09-30,171401,USD,2024,Q3,2024-10-24,2025-11-17,31775000.0,32088000.0,...,-625000.0,-625000.0,3177000.0,NaN,3177000,-795000.0,2382000,NaN,2382000,2382000
50035,ZYXI,2024-12-31,171401,USD,2024,Q4,2025-03-11,2025-11-17,31883000.0,32077000.0,...,-615000.0,-615000.0,-1178000.0,0.0,-1178000,563000.0,-615000,NaN,-615000,-615000
50036,ZYXI,2025-03-31,171401,USD,2025,Q1,2025-04-29,2025-04-29,31604000.0,31604000.0,...,-703000.0,-703000.0,-13800000.0,NaN,-13800000,3404000.0,-10396000,NaN,-10396000,-10396000

In [ ]:
cashflow_df = sf.load_cashflow(variant = "quarterly", market = "us").reset_index()
cashflow_df

Dataset "us-cashflow-quarterly" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,2020-07-31,45846,USD,2020,Q3,2020-09-01,2021-06-01,309000000.0,312000000.0,...,290000000.0,-24000000.0,NaN,NaN,-32000000.0,-56000000.0,-161000000.0,-9000000.0,-231000000.0,35000000
1,A,2020-10-31,45846,USD,2020,Q4,2020-12-18,2021-09-01,308000000.0,311000000.0,...,377000000.0,-27000000.0,NaN,NaN,-27000000.0,-55000000.0,35000000.0,-246000000.0,-269000000.0,83000000
2,A,2021-01-31,45846,USD,2021,Q1,2021-03-02,2022-03-03,306000000.0,309000000.0,...,238000000.0,-41000000.0,NaN,NaN,-42000000.0,-59000000.0,134000000.0,-319000000.0,-316000000.0,-111000000
3,A,2021-04-30,45846,USD,2021,Q2,2021-06-01,2022-03-03,306000000.0,306000000.0,...,472000000.0,-31000000.0,NaN,-547000000.0,-587000000.0,-59000000.0,427000000.0,-194000000.0,166000000.0,51000000
4,A,2021-07-31,45846,USD,2021,Q3,2021-09-01,2022-05-31,303000000.0,306000000.0,...,334000000.0,-54000000.0,NaN,0.0,-61000000.0,-59000000.0,-75000000.0,-87000000.0,-222000000.0,48000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50024,ZYXI,2024-03-31,171401,USD,2024,Q1,2024-04-30,2025-04-29,32344000.0,32827000.0,...,2068000.0,-153000.0,NaN,NaN,-153000.0,-3000.0,-123000.0,-13267000.0,-13633000.0,-11718000
50025,ZYXI,2024-06-30,171401,USD,2024,Q2,2024-07-25,2025-04-29,31762000.0,32204000.0,...,1134000.0,-137000.0,NaN,NaN,-137000.0,0.0,-498000.0,-2345000.0,-2962000.0,-1965000
50026,ZYXI,2024-09-30,171401,USD,2024,Q3,2024-10-24,2025-07-31,31775000.0,32088000.0,...,7074000.0,-72000.0,NaN,NaN,-72000.0,-6000.0,-55000.0,0.0,-268000.0,6734000
50027,ZYXI,2024-12-31,171401,USD,2024,Q4,2025-03-11,2025-11-17,31883000.0,32077000.0,...,2445000.0,-216000.0,NaN,NaN,-216000.0,0.0,-131000.0,9000.0,-228000.0,2001000
50028,ZYXI,2025-03-31,171401,USD,2025,Q1,2025-04-29,2025-04-29,31604000.0,31604000.0,...,-10503000.0,-168000.0,NaN,NaN,-168000.0,NaN,-39000.0,-4932000.0,-5108000.0,-15779000

In [ ]:
balance_df = sf.load_balance(variant = "quarterly", market = "us").reset_index()
balance_df

Dataset "us-balance-quarterly" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity
0,A,2020-07-31,45846,USD,2020,Q3,2020-09-01,2020-09-01,309000000.0,312000000.0,...,40000000.0,1.314000e+09,2.283000e+09,3.251000e+09,4.565000e+09,5.327000e+09,NaN,130000000.0,4.981000e+09,9546000000
1,A,2020-10-31,45846,USD,2020,Q4,2020-12-18,2021-12-17,308000000.0,311000000.0,...,75000000.0,1.467000e+09,2.284000e+09,3.287000e+09,4.754000e+09,5.314000e+09,NaN,81000000.0,4.873000e+09,9627000000
2,A,2021-01-31,45846,USD,2021,Q1,2021-03-02,2021-03-02,306000000.0,309000000.0,...,314000000.0,1.687000e+09,2.185000e+09,3.183000e+09,4.870000e+09,5.269000e+09,NaN,4000000.0,4.804000e+09,9674000000
3,A,2021-04-30,45846,USD,2021,Q2,2021-06-01,2021-06-01,306000000.0,306000000.0,...,205000000.0,1.758000e+09,2.727000e+09,3.830000e+09,5.588000e+09,5.274000e+09,NaN,-12000000.0,4.810000e+09,10398000000
4,A,2021-07-31,45846,USD,2021,Q3,2021-09-01,2021-09-01,303000000.0,306000000.0,...,130000000.0,1.724000e+09,2.728000e+09,3.821000e+09,5.545000e+09,5.310000e+09,NaN,90000000.0,4.946000e+09,10491000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50028,ZYXI,2024-03-31,171401,USD,2024,Q1,2024-04-30,2024-04-30,32344000.0,32827000.0,...,NaN,2.175500e+07,5.783900e+07,7.137000e+07,9.312500e+07,9.129100e+07,-84981000.0,26790000.0,3.310000e+07,126225000
50029,ZYXI,2024-06-30,171401,USD,2024,Q2,2024-07-25,2024-07-25,31762000.0,32204000.0,...,NaN,1.823800e+07,5.807800e+07,7.086100e+07,8.909900e+07,9.199500e+07,-87186000.0,28007000.0,3.281600e+07,121915000
50030,ZYXI,2024-09-30,171401,USD,2024,Q3,2024-10-24,2024-10-24,31775000.0,32088000.0,...,NaN,1.986800e+07,5.832000e+07,7.041800e+07,9.028600e+07,9.257000e+07,-87186000.0,30389000.0,3.577300e+07,126059000
50031,ZYXI,2024-12-31,171401,USD,2024,Q4,2025-03-11,2025-11-17,31883000.0,32077000.0,...,NaN,1.686400e+07,5.856700e+07,6.950700e+07,8.637100e+07,9.312000e+07,-87186000.0,29774000.0,3.570800e+07,122079000
50032,ZYXI,2025-03-31,171401,USD,2025,Q1,2025-04-29,2025-04-29,31604000.0,31604000.0,...,NaN,1.631700e+07,5.881800e+07,6.866800e+07,8.498500e+07,9.351900e+07,-92123000.0,19378000.0,2.077400e+07,105759000

In [ ]:
income_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50037 entries, 0 to 50036
Data columns (total 28 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Ticker                                    50037 non-null  str
 1   Report Date                               50037 non-null  datetime64[us]
 2   SimFinId                                  50037 non-null  int64
 3   Currency                                  50037 non-null  str
 4   Fiscal Year                               50037 non-null  int64
 5   Fiscal Period                             50037 non-null  str
 6   Publish Date                              50037 non-null  datetime64[us]
 7   Restated Date                             50037 non-null  datetime64[us]
 8   Shares (Basic)                            49716 non-null  float64
 9   Shares (Diluted)                          49609 non-null  float64
 10  Revenue                                   44456 non-null  float64
 11  Cost of Revenue                           39131 non-null  float64
 12  Gross Profit                              39143 non-null  float64
 13  Operating Expenses                        49952 non-null  float64
 14  Selling, General & Administrative         47793 non-null  float64
 15  Research & Development                    24562 non-null  float64
 16  Depreciation & Amortization               20128 non-null  float64
 17  Operating Income (Loss)                   50035 non-null  float64
 18  Non-Operating Income (Loss)               49505 non-null  float64
 19  Interest Expense, Net                     43460 non-null  float64
 20  Pretax Income (Loss), Adj.                50036 non-null  float64
 21  Abnormal Gains (Losses)                   27017 non-null  float64
 22  Pretax Income (Loss)                      50037 non-null  int64
 23  Income Tax (Expense) Benefit, Net         39324 non-null  float64
 24  Income (Loss) from Continuing Operations  50037 non-null  int64
 25  Net Extraordinary Gains (Losses)          3004 non-null   float64
 26  Net Income                                50037 non-null  int64
 27  Net Income (Common)                       50037 non-null  int64
dtypes: datetime64[us](3), float64(16), int64(6), str(3)
memory usage: 10.7 MB

In [ ]:
balance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50033 entries, 0 to 50032
Data columns (total 30 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Ticker                                           50033 non-null  str
 1   Report Date                                      50033 non-null  datetime64[us]
 2   SimFinId                                         50033 non-null  int64
 3   Currency                                         50033 non-null  str
 4   Fiscal Year                                      50033 non-null  int64
 5   Fiscal Period                                    50033 non-null  str
 6   Publish Date                                     50033 non-null  datetime64[us]
 7   Restated Date                                    50033 non-null  datetime64[us]
 8   Shares (Basic)                                   49715 non-null  float64
 9   Shares (Diluted)                                 49608 non-null  float64
 10  Cash, Cash Equivalents & Short Term Investments  49868 non-null  float64
 11  Accounts & Notes Receivable                      39560 non-null  float64
 12  Inventories                                      27126 non-null  float64
 13  Total Current Assets                             50030 non-null  float64
 14  Property, Plant & Equipment, Net                 46655 non-null  float64
 15  Long Term Investments & Receivables              11519 non-null  float64
 16  Other Long Term Assets                           48309 non-null  float64
 17  Total Noncurrent Assets                          49691 non-null  float64
 18  Total Assets                                     50033 non-null  int64
 19  Payables & Accruals                              49867 non-null  float64
 20  Short Term Debt                                  26231 non-null  float64
 21  Total Current Liabilities                        49984 non-null  float64
 22  Long Term Debt                                   35909 non-null  float64
 23  Total Noncurrent Liabilities                     48537 non-null  float64
 24  Total Liabilities                                50024 non-null  float64
 25  Share Capital & Additional Paid-In Capital       49404 non-null  float64
 26  Treasury Stock                                   16852 non-null  float64
 27  Retained Earnings                                48099 non-null  float64
 28  Total Equity                                     50028 non-null  float64
 29  Total Liabilities & Equity                       50033 non-null  int64
dtypes: datetime64[us](3), float64(20), int64(4), str(3)
memory usage: 11.5 MB

In [ ]:
cashflow_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50029 entries, 0 to 50028
Data columns (total 28 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Ticker                                     50029 non-null  str
 1   Report Date                                50029 non-null  datetime64[us]
 2   SimFinId                                   50029 non-null  int64
 3   Currency                                   50029 non-null  str
 4   Fiscal Year                                50029 non-null  int64
 5   Fiscal Period                              50029 non-null  str
 6   Publish Date                               50029 non-null  datetime64[us]
 7   Restated Date                              50029 non-null  datetime64[us]
 8   Shares (Basic)                             49708 non-null  float64
 9   Shares (Diluted)                           49601 non-null  float64
 10  Net Income/Starting Line                   49577 non-null  float64
 11  Depreciation & Amortization                47415 non-null  float64
 12  Non-Cash Items                             49508 non-null  float64
 13  Change in Working Capital                  49609 non-null  float64
 14  Change in Accounts Receivable              611 non-null    float64
 15  Change in Inventories                      420 non-null    float64
 16  Change in Accounts Payable                 522 non-null    float64
 17  Change in Other                            809 non-null    float64
 18  Net Cash from Operating Activities         50027 non-null  float64
 19  Change in Fixed Assets & Intangibles       45642 non-null  float64
 20  Net Change in Long Term Investment         17662 non-null  float64
 21  Net Cash from Acquisitions & Divestitures  16083 non-null  float64
 22  Net Cash from Investing Activities         48323 non-null  float64
 23  Dividends Paid                             17306 non-null  float64
 24  Cash from (Repayment of) Debt              37052 non-null  float64
 25  Cash from (Repurchase of) Equity           38311 non-null  float64
 26  Net Cash from Financing Activities         48897 non-null  float64
 27  Net Change in Cash                         50029 non-null  int64
dtypes: datetime64[us](3), float64(19), int64(3), str(3)
memory usage: 10.7 MB

In [ ]:
income_df = pd.read_csv("income_statement.csv")
income_df

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
0,A,1/31/2017,45846,USD,2017,Q1,3/8/2017,3/6/2018,322000000.0,326000000.0,...,-13000000.0,-16000000.0,193000000,NaN,193000000,-25000000.0,168000000,NaN,168000000,168000000
1,A,4/30/2017,45846,USD,2017,Q2,6/6/2017,5/31/2018,321000000.0,325000000.0,...,-10000000.0,-15000000.0,191000000,NaN,191000000,-27000000.0,164000000,NaN,164000000,164000000
2,A,7/31/2017,45846,USD,2017,Q3,9/6/2017,8/30/2018,321000000.0,326000000.0,...,-8000000.0,-13000000.0,193000000,NaN,193000000,-18000000.0,175000000,NaN,175000000,175000000
3,A,10/31/2017,45846,USD,2017,Q4,12/21/2017,12/20/2018,324000000.0,327000000.0,...,-7000000.0,-13000000.0,226000000,NaN,226000000,-49000000.0,177000000,NaN,177000000,177000000
4,A,1/31/2018,45846,USD,2018,Q1,3/6/2018,3/5/2019,323000000.0,323000000.0,...,4000000.0,-11000000.0,233000000,NaN,233000000,-553000000.0,-320000000,NaN,-320000000,-320000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,9/30/2020,171401,USD,2020,Q3,10/27/2020,7/29/2021,37945600.0,39035700.0,...,-5000.0,-5000.0,1404000,NaN,1404000,-71000.0,1333000,NaN,1333000,1333000
41575,ZYXI,12/31/2020,171401,USD,2020,Q4,2/25/2021,11/2/2021,38262400.0,39189700.0,...,-5000.0,-5000.0,2292000,-77000.0,2215000,-428000.0,1787000,NaN,1787000,1787000
41576,ZYXI,3/31/2021,171401,USD,2021,Q1,4/29/2021,4/28/2022,38320700.0,38320700.0,...,-9000.0,-9000.0,-1090000,NaN,-1090000,384000.0,-706000,NaN,-706000,-706000
41577,ZYXI,6/30/2021,171401,USD,2021,Q2,7/29/2021,4/28/2022,38320700.0,38320700.0,...,-45000.0,-45000.0,3770000,NaN,3770000,-962000.0,2808000,NaN,2808000,2808000
41578,ZYXI,9/30/2021,171401,USD,2021,Q3,11/2/2021,10/27/2022,38285500.0,39141300.0,...,-18000.0,-18000.0,8028000,NaN,8028000,-1921000.0,6107000,NaN,6107000,6107000

In [ ]:
balance_df = pd.read_csv("balance_sheet.csv")
balance_df

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity
0,A,1/31/2017,45846,USD,2017,Q1,3/8/2017,3/8/2017,322000000.0,326000000.0,...,190000000.0,1.089000e+09,1.802000e+09,2.483000e+09,3.572000e+09,5.239000e+09,0.0,-453000000.0,4.300000e+09,7.872000e+09
1,A,4/30/2017,45846,USD,2017,Q2,6/6/2017,6/6/2017,321000000.0,325000000.0,...,241000000.0,1.187000e+09,1.802000e+09,2.454000e+09,3.641000e+09,5.242000e+09,0.0,-393000000.0,4.375000e+09,8.016000e+09
2,A,7/31/2017,45846,USD,2017,Q3,9/6/2017,9/6/2017,321000000.0,326000000.0,...,280000000.0,1.241000e+09,1.801000e+09,2.409000e+09,3.650000e+09,5.285000e+09,0.0,-260000000.0,4.611000e+09,8.261000e+09
3,A,10/31/2017,45846,USD,2017,Q4,12/21/2017,12/20/2018,324000000.0,327000000.0,...,210000000.0,1.263000e+09,1.801000e+09,2.328000e+09,3.591000e+09,5.303000e+09,NaN,-126000000.0,4.835000e+09,8.426000e+09
4,A,1/31/2018,45846,USD,2018,Q1,3/6/2018,3/6/2018,323000000.0,323000000.0,...,345000000.0,1.361000e+09,1.800000e+09,2.811000e+09,4.172000e+09,5.323000e+09,-3000000.0,-529000000.0,4.526000e+09,8.698000e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,9/30/2020,171401,USD,2020,Q3,10/27/2020,10/27/2020,37945600.0,39035700.0,...,NaN,7.295000e+06,NaN,3.448000e+06,1.074300e+07,3.651400e+07,-3846000.0,21643000.0,5.422200e+07,6.496500e+07
41575,ZYXI,12/31/2020,171401,USD,2020,Q4,2/25/2021,3/22/2022,38262400.0,39189700.0,...,NaN,1.011700e+07,NaN,5.203000e+06,1.532000e+07,3.723500e+07,-3846000.0,23430000.0,5.685500e+07,7.217500e+07
41576,ZYXI,3/31/2021,171401,USD,2021,Q1,4/29/2021,4/29/2021,38320700.0,38320700.0,...,NaN,9.315000e+06,NaN,4.768000e+06,1.408300e+07,3.735000e+07,-3921000.0,22724000.0,5.615300e+07,7.023600e+07
41577,ZYXI,6/30/2021,171401,USD,2021,Q2,7/29/2021,7/29/2021,38320700.0,38320700.0,...,NaN,8.891000e+06,NaN,1.750700e+07,2.639800e+07,3.773400e+07,-5966000.0,25532000.0,5.730000e+07,8.369800e+07
41578,ZYXI,9/30/2021,171401,USD,2021,Q3,11/2/2021,11/2/2021,38285500.0,39141300.0,...,NaN,1.029200e+07,NaN,1.704800e+07,2.734000e+07,3.825700e+07,-6513000.0,31639000.0,6.338300e+07,9.072300e+07

In [ ]:
cashflow_df = pd.read_csv("cashflow_statement.csv")
cashflow_df

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,1/31/2017,45846,USD,2017,Q1,3/8/2017,3/6/2018,322000000.0,326000000.0,...,116000000.0,-32000000.0,NaN,-69000000.0,-101000000.0,-42000000.0,89000000.0,-93000000.0,-58000000.0,-48000000
1,A,4/30/2017,45846,USD,2017,Q2,6/6/2017,5/31/2018,321000000.0,325000000.0,...,257000000.0,-43000000.0,NaN,0.0,-43000000.0,-43000000.0,52000000.0,-75000000.0,-67000000.0,148000000
2,A,7/31/2017,45846,USD,2017,Q3,9/6/2017,8/30/2018,321000000.0,326000000.0,...,228000000.0,-43000000.0,NaN,-57000000.0,-101000000.0,-42000000.0,39000000.0,32000000.0,29000000.0,174000000
3,A,10/31/2017,45846,USD,2017,Q4,12/21/2017,12/20/2018,324000000.0,327000000.0,...,288000000.0,-58000000.0,0.0,0.0,-60000000.0,-43000000.0,-70000000.0,8000000.0,-106000000.0,115000000
4,A,1/31/2018,45846,USD,2018,Q1,3/6/2018,3/5/2019,323000000.0,323000000.0,...,215000000.0,-60000000.0,NaN,-6000000.0,-67000000.0,-48000000.0,135000000.0,-22000000.0,37000000.0,210000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41574,ZYXI,9/30/2020,171401,USD,2020,Q3,10/27/2020,7/29/2021,37945600.0,39035700.0,...,-769000.0,-105000.0,NaN,NaN,-105000.0,NaN,-15000.0,25202000.0,25187000.0,24313000
41575,ZYXI,12/31/2020,171401,USD,2020,Q4,2/25/2021,11/2/2021,38262400.0,39189700.0,...,-1696000.0,-226000.0,NaN,NaN,-226000.0,NaN,-15000.0,293000.0,-134000.0,-2056000
41576,ZYXI,3/31/2021,171401,USD,2021,Q1,4/29/2021,4/28/2022,38320700.0,38320700.0,...,-5305000.0,-299000.0,NaN,NaN,-299000.0,NaN,-23000.0,-48000.0,-130000.0,-5734000
41577,ZYXI,6/30/2021,171401,USD,2021,Q2,7/29/2021,4/28/2022,38320700.0,38320700.0,...,1027000.0,-55000.0,NaN,NaN,-55000.0,NaN,-21000.0,-1984000.0,-2081000.0,-1109000
41578,ZYXI,9/30/2021,171401,USD,2021,Q3,11/2/2021,7/28/2022,38285500.0,39141300.0,...,3689000.0,-66000.0,NaN,NaN,-66000.0,NaN,-29000.0,-508000.0,-585000.0,3038000

In [ ]:
industries_info_df = pd.read_csv("industries_information.csv")
industries_info_df.head(70)
industries_info_df.tail(5)

    IndustryId           Sector              Industry
69      110004  Basic Materials       Metals & Mining
70      110005  Basic Materials    Building Materials
71      110006  Basic Materials                  Coal
72      110007  Basic Materials                 Steel
73      111001            Other  Diversified Holdings

In [ ]:
us_info_df =pd.read_csv("companies_information.csv")
us_info_df.head(15)

   Ticker  SimFinId                      Company Name  IndustryId
0       A     45846          AGILENT TECHNOLOGIES INC    106001.0
1     A21   1333027                      Li Auto Inc.         NaN
2      AA    367153                        Alcoa Corp    110004.0
3     AAL     68568      American Airlines Group Inc.    100006.0
4    AAMC    847094  Altisource Asset Management Corp    104001.0
5    AAME    450021            ATLANTIC AMERICAN CORP    104004.0
6     AAN    441241             Aaron's Company, Inc.    100007.0
7    AAOI    671827     APPLIED OPTOELECTRONICS, INC.    101004.0
8    AAON    919501                          AAON INC    100001.0
9     AAP    184955            ADVANCE AUTO PARTS INC    103002.0
10   AAPL    111052                         APPLE INC    101001.0
11    AAT    919944       American Assets Trust, Inc.    109001.0
12   AAWW    762204  ATLAS AIR WORLDWIDE HOLDINGS INC    100010.0
13   ABAX     36105                        ABAXIS INC    106001.0
14   ABBV     61199                       AbbVie Inc.    106005.0

In [ ]:
## Filtering out data from Pandas Dataframe

us_info_df[us_info_df["Company Name"]=="APPLE INC"]

   Ticker  SimFinId Company Name  IndustryId
10   AAPL    111052    APPLE INC    101001.0

In [ ]:
## Merge all Pandas Dataframes

companies_info_df = pd.read_csv("companies_information.csv")
industries_info_df
companies_industries_df = pd.merge(companies_info_df,industries_info_df,on = "IndustryId",how = "left")
companies_industries_df

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry
0,A,45846,AGILENT TECHNOLOGIES INC,106001.0,Healthcare,Medical Diagnostics & Research
1,A21,1333027,Li Auto Inc.,NaN,NaN,NaN
2,AA,367153,Alcoa Corp,110004.0,Basic Materials,Metals & Mining
3,AAL,68568,American Airlines Group Inc.,100006.0,Industrials,Airlines
4,AAMC,847094,Altisource Asset Management Corp,104001.0,Financial Services,Asset Management
...,...,...,...,...,...,...
3117,ZUO,994625,ZUORA INC,101003.0,Technology,Application Software
3118,ZVO,901866,Zovio Inc,102006.0,Consumer Defensive,Education
3119,ZY,1243193,Zymergen Inc.,106002.0,Healthcare,Biotechnology
3120,ZYNE,901704,"Zynerba Pharmaceuticals, Inc.",106002.0,Healthcare,Biotechnology
3121,ZYXI,171401,ZYNEX INC,106004.0,Healthcare,Medical Devices

In [96]:
### Merging multiple Pandas Dataframes together

epf_df = pd.read_csv("eps_df.csv")
epf_df

### Drop/Remove Duplicate columns across financial statements 

cashflow_df = pd.read_csv("cashflow_statement.csv")
cashflow_df = cashflow_df.drop(columns = ["Report Date",
                                          "Currency",
                                          "Publish Date",
                                          "Restated Date",
                                          "Shares (Basic)",
                                          "Shares (Diluted)",
                                          "Depreciation & Amortization"])


balance_df = pd.read_csv("balance_sheet.csv")
balance_df = balance_df.drop(columns = ["Report Date",
                                        "Currency",
                                          "Publish Date",
                                          "Restated Date",
                                          "Shares (Basic)",
                                          "Shares (Diluted)"])
balance_df


income_df = pd.read_csv("income_statement.csv")

In [100]:
### Merging all the income statement, cash flow statement and balance sheet together

merged_df = companies_industries_df.merge(income_df, on = ["Ticker","SimFinId"],how = "left")\
                                                           .merge(cashflow_df, on =["Ticker","SimFinId","Fiscal Year","Fiscal Period"],how ="left")\
                                                           .merge(balance_df, on =["Ticker","SimFinId","Fiscal Year","Fiscal Period"],how ="left")\
                                                           .merge(epf_df, on =["Ticker","Fiscal Year","Fiscal Period"], how ="left")

merged_df = merged_df.drop(columns =["SimFinId", "IndustryId"])
merged_df

,Ticker,Company Name,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,...,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,"Earnings Per Share, Basic"
0,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,1/31/2017,USD,2017.0,Q1,3/8/2017,3/6/2018,...,1.089000e+09,1.802000e+09,2.483000e+09,3.572000e+09,5.239000e+09,0.0,-453000000.0,4.300000e+09,7.872000e+09,0.52174
1,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,4/30/2017,USD,2017.0,Q2,6/6/2017,5/31/2018,...,1.187000e+09,1.802000e+09,2.454000e+09,3.641000e+09,5.242000e+09,0.0,-393000000.0,4.375000e+09,8.016000e+09,0.51090
2,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,7/31/2017,USD,2017.0,Q3,9/6/2017,8/30/2018,...,1.241000e+09,1.801000e+09,2.409000e+09,3.650000e+09,5.285000e+09,0.0,-260000000.0,4.611000e+09,8.261000e+09,0.54517
3,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,10/31/2017,USD,2017.0,Q4,12/21/2017,12/20/2018,...,1.263000e+09,1.801000e+09,2.328000e+09,3.591000e+09,5.303000e+09,NaN,-126000000.0,4.835000e+09,8.426000e+09,0.54630
4,A,AGILENT TECHNOLOGIES INC,Healthcare,Medical Diagnostics & Research,1/31/2018,USD,2018.0,Q1,3/6/2018,3/5/2019,...,1.361000e+09,1.800000e+09,2.811000e+09,4.172000e+09,5.323000e+09,-3000000.0,-529000000.0,4.526000e+09,8.698000e+09,-0.99071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42157,ZYXI,ZYNEX INC,Healthcare,Medical Devices,9/30/2020,USD,2020.0,Q3,10/27/2020,7/29/2021,...,7.295000e+06,NaN,3.448000e+06,1.074300e+07,3.651400e+07,-3846000.0,21643000.0,5.422200e+07,6.496500e+07,0.03513
42158,ZYXI,ZYNEX INC,Healthcare,Medical Devices,12/31/2020,USD,2020.0,Q4,2/25/2021,11/2/2021,...,1.011700e+07,NaN,5.203000e+06,1.532000e+07,3.723500e+07,-3846000.0,23430000.0,5.685500e+07,7.217500e+07,0.04670
42159,ZYXI,ZYNEX INC,Healthcare,Medical Devices,3/31/2021,USD,2021.0,Q1,4/29/2021,4/28/2022,...,9.315000e+06,NaN,4.768000e+06,1.408300e+07,3.735000e+07,-3921000.0,22724000.0,5.615300e+07,7.023600e+07,-0.01842
42160,ZYXI,ZYNEX INC,Healthcare,Medical Devices,6/30/2021,USD,2021.0,Q2,7/29/2021,4/28/2022,...,8.891000e+06,NaN,1.750700e+07,2.639800e+07,3.773400e+07,-5966000.0,25532000.0,5.730000e+07,8.369800e+07,0.07328
42161,ZYXI,ZYNEX INC,Healthcare,Medical Devices,9/30/2021,USD,2021.0,Q3,11/2/2021,10/27/2022,...,1.029200e+07,NaN,1.704800e+07,2.734000e+07,3.825700e+07,-6513000.0,31639000.0,6.338300e+07,9.072300e+07,0.15951